language: cpp

sudo: required

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

install:
  - make get-deps
  - echo $LANG
  - echo $LC_ALL

before_script:
  - mkdir build
  - cd build
  - cmake

script: make
